### ISSUE TITLE
TypeError: Cannot read property 'lgUser' of undefined

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/rocketchat-lg-sso#16]
Trying to work through issues with running the system locally.

Finding this output being repeated in the chat window console:

```
[LG SSO] fetching new JWT token and updating user info
debug.js:41 Exception in setInterval callback: TypeError: Cannot read property 'lgUser' of undefined
    at fetchJWTAndUpdateUserInfo (http://chat.learnersguild.dev/packages/learnersguild_rocketchat-lg-sso.js?1a7b5a0b3cf2fa08db5ff4b1bf893c542d779fee:265:43)
    at _.extend.withValue (http://chat.learnersguild.dev/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:971:17)
    at http://chat.learnersguild.dev/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:428:45
    at http://chat.learnersguild.dev/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:999:22
```

A couple of issues are easy to identify:
- We should be more defensive in our handling of values returned from the meteor service.
- There's no indication in the UX of any auth failure

Not sure what else might need to be addressed..

**Comment by jeffreywescott** [comment]
This is super weird. The only way this should ever happen is if the user never authenticated, but if they never authenticated, that code shouldn't be running at all. Do you remember the circumstances under which this happened? Did you get past this error?
